fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    ruby: "git://github.com/puppetlabs/puppetlabs-ruby.git"
    gcc: "git://github.com/puppetlabs/puppetlabs-gcc.git"
  symlinks:
    mailcatcher: "#{source_dir}"
